In [1]:
import numpy as np
def CountInt(A):
    result = []
    for i in range(6):
        result.append(np.count_nonzero(A==i))
    return np.array(result)
CountInt(np.array([3,2,4,5,2]))

array([0, 0, 2, 1, 1, 1])

In [2]:
def CountInt2(A):
    result= []
    for i in range(np.max(A)+1):
        result.append(np.count_nonzero(A==i))
    return np.array(result)
CountInt2(np.random.randint(0,100,100))

array([3, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 3, 1, 0, 0, 3, 2, 2, 1,
       1, 1, 1, 2, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 2, 2, 0, 0, 1, 3, 3,
       0, 1, 1, 0, 1, 1, 2, 1, 0, 0, 3, 1, 2, 1, 2, 1, 2, 2, 0, 2, 1, 0, 2,
       1, 0, 0, 0, 2, 0, 2, 1, 0, 0, 3, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 3, 3,
       0, 0, 1, 1, 2, 0, 1])

In [6]:
def CountInt3(A):
    N = np.max(A)+1
    time= np.zeros(N)
    for i in range(len(A)):
        v=A[i]
        time[v]=time[v]+1
    return time
CountInt3(np.random.randint(0,100,100))

array([ 1.,  1.,  3.,  1.,  2.,  1.,  4.,  1.,  1.,  0.,  1.,  0.,  0.,
        2.,  1.,  0.,  1.,  2.,  1.,  2.,  0.,  0.,  1.,  2.,  0.,  0.,
        0.,  2.,  0.,  1.,  3.,  1.,  0.,  0.,  1.,  0.,  1.,  2.,  1.,
        3.,  3.,  1.,  1.,  0.,  0.,  1.,  1.,  3.,  0.,  1.,  1.,  0.,
        0.,  0.,  0.,  0.,  3.,  1.,  3.,  0.,  1.,  1.,  0.,  1.,  2.,
        1.,  0.,  0.,  0.,  1.,  2.,  3.,  2.,  1.,  0.,  0.,  1.,  2.,
        2.,  1.,  3.,  0.,  1.,  0.,  1.,  1.,  0.,  2.,  0.,  0.,  1.,
        0.,  1.,  1.,  2.,  0.,  0.,  0.,  4.])