In [1]:
%matplotlib inline
import numpy as np
import pylab
import urllib

# let's fetch the data
urllib.request.urlretrieve('https://goo.gl/mjDtMB', 'hourly.pkl')

import pickle
hourly = pickle.load(open('hourly.pkl', 'rb'))
hourly[:10]

array([[21,  1,  1,  0,  3],
       [18,  1,  1,  1,  3],
       [ 0,  1,  1,  2,  3],
       [ 0,  1,  1,  3,  3],
       [ 0,  1,  1,  4,  3],
       [ 0,  1,  1,  5,  3],
       [ 3,  1,  1,  6,  3],
       [12,  1,  1,  7,  3],
       [ 4,  1,  1,  8,  3],
       [11,  1,  1,  9,  3]])

In [23]:
def f1(A, N): #longest run in A with less than N books read 
    run= 0
    runs= []
    for i in range(len(A[:,0])):
        if A[i,0] < N:
            run = run +1
            runs.append(run)
        else: 
            run =0
    return np.max(runs)
F1(hourly, 10)

15

In [24]:
def f2(A, N): #longest run in A with less than N books read 
    run= 0
    maxrun = 0
    for i in range(len(A[:,0])):
        if A[i,0] < N:
            run = run +1
            if run > maxrun:
                maxrun = run
        else: 
            run =0
    return maxrun
F1(hourly, 10)

15

In [28]:
def f3(A): #essentially the np.bincount function
    R = np.zeros(np.max(A+1), dtype=int)
    for i in range(len(A)):
        R[A[i]] = R[A[i]]+1
    return R
f3(hourly[:10,0])

array([4, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1])

In [39]:
def f4(A): #returns the length of the longest run of increasing numbers (not including first number in run)
    run=0
    maxrun= 0
    B=A[:,0]
    for i in range(len(B)):
        if i > 0:
            if B[i]> B[i-1]:
                run= run +1
                if run >maxrun:
                    maxrun = run
            else: run =0
    return maxrun
f4(hourly)

9

In [45]:
def f5(A): #returns the longest run of increasing numbers
    run = 0
    maxrun = 0
    maxindex = 0
    for i in range(1, len(A)):
        if A[i,0] > A[i-1,0]:
            run = run + 1
            if run > maxrun:
                maxrun = run
                maxindex = i
            #print(i, run)
        else:
            run = 0
    return A[maxindex-maxrun:maxindex+1,0]
f5(hourly) 

array([  5,   7,  10,  14,  74, 224, 348, 604, 697, 862])