In [1]:
import numpy as np

#load the list of the first million primes
primes = np.genfromtxt("http://wwwx.cs.unc.edu/Courses/comp116-001-f16/media/primes.txt",
                      dtype=int)

In [2]:
len(primes)

1000000

In [3]:
primes[:20]

array([ 2,  3,  5,  7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47, 53, 59,
       61, 67, 71])

In [4]:
primes[-5:]

array([15485837, 15485843, 15485849, 15485857, 15485863])

In [12]:
np.bincount(primes % 10)

array([     0, 249934,      1, 250110,      0,      1,      0, 250014,
            0, 249940])

In [8]:
LastDigit(10, primes)

array([     0, 249934,      1, 250110,      0,      1,      0, 250014,
            0, 249940])

In [19]:
B =10
DC = {}
for i in range(len(primes)):
    ld = primes[i] % B
    DC[ld]= DC.get(ld,0)+1
DC

{1: 249934, 2: 1, 3: 250110, 5: 1, 7: 250014, 9: 249940}

In [24]:
PC = {}
for i in range(1, len(primes)):
    ld1 = primes[i-1] % B
    ld2 = primes[i] % B
    key = (ld1, ld2)
    PC[key] = PC.get(key, 0) + 1
    
PC

{(1, 1): 42853,
 (1, 3): 77475,
 (1, 7): 79453,
 (1, 9): 50153,
 (2, 3): 1,
 (3, 1): 58255,
 (3, 3): 39668,
 (3, 5): 1,
 (3, 7): 72827,
 (3, 9): 79358,
 (5, 7): 1,
 (7, 1): 64230,
 (7, 3): 68595,
 (7, 7): 39603,
 (7, 9): 77586,
 (9, 1): 84596,
 (9, 3): 64371,
 (9, 7): 58130,
 (9, 9): 42843}

In [28]:
PC = {}
for i in range(1, len(primes)):
    ld1 = primes[i-1] % B
    ld2 = primes[i] % B
    key = ld1*B + ld2
    PC[key] = PC.get(key, 0) + 1
    
PC

{11: 42853,
 13: 77475,
 17: 79453,
 19: 50153,
 23: 1,
 31: 58255,
 33: 39668,
 35: 1,
 37: 72827,
 39: 79358,
 57: 1,
 71: 64230,
 73: 68595,
 77: 39603,
 79: 77586,
 91: 84596,
 93: 64371,
 97: 58130,
 99: 42843}

In [30]:
B = 10
PC = np.zeros((B, B), dtype=int)
for i in range(1, len(primes)):
    ld1 = primes[i-1] % B
    ld2 = primes[i] % B
    PC[ld1, ld2] += 1
    
PC

array([[    0,     0,     0,     0,     0,     0,     0,     0,     0,
            0],
       [    0, 42853,     0, 77475,     0,     0,     0, 79453,     0,
        50153],
       [    0,     0,     0,     1,     0,     0,     0,     0,     0,
            0],
       [    0, 58255,     0, 39668,     0,     1,     0, 72827,     0,
        79358],
       [    0,     0,     0,     0,     0,     0,     0,     0,     0,
            0],
       [    0,     0,     0,     0,     0,     0,     0,     1,     0,
            0],
       [    0,     0,     0,     0,     0,     0,     0,     0,     0,
            0],
       [    0, 64230,     0, 68595,     0,     0,     0, 39603,     0,
        77586],
       [    0,     0,     0,     0,     0,     0,     0,     0,     0,
            0],
       [    0, 84596,     0, 64371,     0,     0,     0, 58130,     0,
        42843]])