In [1]:
%matplotlib inline
import numpy as np
import pylab

In [28]:
np.random.seed(0) # this forces the "random" number generator to give us all the same numbers
data = np.random.randint(1, 100, (4, 5))
print(data)

[[45 48 65 68 68]
 [10 84 22 37 88]
 [71 89 89 13 59]
 [66 40 88 47 89]]


In [4]:
print(data[1,2])

22

In [29]:
data[1,2]= 42
print(data)

[[45 48 65 68 68]
 [10 84 42 37 88]
 [71 89 89 13 59]
 [66 40 88 47 89]]


In [6]:
data[:,1]

array([48, 84, 89, 40])

In [7]:
data[1:3,1:4]

array([[84, 42, 37],
       [89, 89, 13]])

In [9]:
data[1:3,1:4]=0
data

array([[45, 48, 65, 68, 68],
       [10,  0,  0,  0, 88],
       [71,  0,  0,  0, 59],
       [66, 40, 88, 47, 89]])

In [12]:
data[1:3,1:4]=np.random.randint(100,200,(2,3))
data

array([[ 45,  48,  65,  68,  68],
       [ 10, 120, 180, 169,  88],
       [ 71, 179, 147, 164,  59],
       [ 66,  40,  88,  47,  89]])

In [30]:
data[0,::2]=0
print(data)

[[ 0 48  0 68  0]
 [10 84 42 37 88]
 [71 89 89 13 59]
 [66 40 88 47 89]]


In [31]:
data

array([[ 0, 48,  0, 68,  0],
       [10, 84, 42, 37, 88],
       [71, 89, 89, 13, 59],
       [66, 40, 88, 47, 89]])

In [34]:
data[:,:]=-1
data

array([[-1, -1, -1, -1, -1],
       [-1, -1, -1, -1, -1],
       [-1, -1, -1, -1, -1],
       [-1, -1, -1, -1, -1]])

In [37]:
np.zeros((4,4))

array([[ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.]])

In [38]:
np.ones((4,4))

array([[ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.]])

In [40]:
board=np.zeros((4,4))

In [41]:
board[0::2, 0::2]= 1
board[1::2, 1::2]=1
board

array([[ 1.,  0.,  1.,  0.],
       [ 0.,  1.,  0.,  1.],
       [ 1.,  0.,  1.,  0.],
       [ 0.,  1.,  0.,  1.]])