In [1]:
%matplotlib inline
import numpy as np
import pylab

In [4]:
A =np.array([[14,3,19],[19,5,3],[13,2,15]])
A

array([[14,  3, 19],
       [19,  5,  3],
       [13,  2, 15]])

In [5]:
np.diff(A, axis=0)

array([[  5,   2, -16],
       [ -6,  -3,  12]])

In [6]:
np.diff(A, axis=1)

array([[-11,  16],
       [-14,  -2],
       [-11,  13]])

In [10]:
A[1:,:]-A[:-1,:] #???

array([[  5,   2, -16],
       [ -6,  -3,  12]])

In [11]:
def double(x):
    return 2 * x
print(double(3))

6


In [12]:
double (A)

array([[28,  6, 38],
       [38, 10,  6],
       [26,  4, 30]])

In [15]:
def DegreeChange(x):
    return ((x-32)*5/9)
DegreeChange(68)

20.0

In [16]:
DegreeChange(np.arange(0,100,10))

array([-17.77777778, -12.22222222,  -6.66666667,  -1.11111111,
         4.44444444,  10.        ,  15.55555556,  21.11111111,
        26.66666667,  32.22222222])

In [17]:
def CtoF(x):
    return(9/5*x+32)
CtoF(20)

68.0

In [18]:
def sind(x):
    return np.sin(x/180*np.pi)
sind(90)

1.0

In [22]:
def F(x,y):
    z=x+y
    a=x+2*y
    b=z+a
    return b
F(1,2)

8

In [25]:
b='hello world'
print(F(1,2))
b

8


'hello world'

In [26]:
def G(t1, t2):
    a = DegreeChange(t1)
    b= DegreeChange(t2)
    return a-b
    

In [27]:
G(90,76)

7.777777777777779

In [28]:
G(68,32)

20.0