In [2]:
%matplotlib inline
import numpy as np
import pylab

In [5]:
def FtoC(F):
    '''Convert Fahrenheit to Celcius'''
    C= (F-32)*5/9
    return C
def CtoF(C):
    '''Convert Celcius to Fahrenheit'''
    F= C*9/5+32
    return F

In [6]:
def DewPoint(T, RH):
    return T-(100-RH)/5

In [7]:
DewPoint(20,50)

10.0

In [15]:
def DewPointF (Tf, RH):
    return CtoF(DewPoint(FtoC(Tf),RH))

In [13]:
CtoF(20)

68.0

In [17]:
DewPointF(68,50)
DewPointF(100,50)

82.0

In [20]:
T= np.arange(40,110,10)
T

array([ 40,  50,  60,  70,  80,  90, 100])

In [21]:
DewPoint (T, 50)

array([ 30.,  40.,  50.,  60.,  70.,  80.,  90.])

In [22]:
R=np.arange(20,110,10)

In [23]:
DewPoint (70,R)

array([ 54.,  56.,  58.,  60.,  62.,  64.,  66.,  68.,  70.])

In [24]:
T= np.reshape(T,(-1,1))

In [25]:
DewPoint (T,R)

array([[  24.,   26.,   28.,   30.,   32.,   34.,   36.,   38.,   40.],
       [  34.,   36.,   38.,   40.,   42.,   44.,   46.,   48.,   50.],
       [  44.,   46.,   48.,   50.,   52.,   54.,   56.,   58.,   60.],
       [  54.,   56.,   58.,   60.,   62.,   64.,   66.,   68.,   70.],
       [  64.,   66.,   68.,   70.,   72.,   74.,   76.,   78.,   80.],
       [  74.,   76.,   78.,   80.,   82.,   84.,   86.,   88.,   90.],
       [  84.,   86.,   88.,   90.,   92.,   94.,   96.,   98.,  100.]])