In [24]:
A= [1,2,3,4,5,6,7,8,9,10,11,12]
A

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]

In [23]:
%matplotlib inline
import numpy as np
import pylab

In [33]:
B= np.reshape(A, (6,-1))
B

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [32]:
B[2,:]

array([ 9, 10, 11, 12])

In [35]:
DaysOver= B > (2,3)
DaysOver

array([[False, False],
       [ True,  True],
       [ True,  True],
       [ True,  True],
       [ True,  True],
       [ True,  True]], dtype=bool)