In [1]:
%matplotlib inline
import numpy as np
import pylab

In [5]:
oh=np.random.randint(1,100,(5,6))
print(oh)

[[65 25 28 19 45 43]
 [22 63 45 92 70 32]
 [25 36 13 85 44 99]
 [28 67 23 86 27 92]
 [96 55 44 39 13 72]]


In [6]:
np.argmax(np.argmax(oh))

0