# Notes for 28 October

Fun with Midterm2 data

In [1]:
%matplotlib inline
import numpy as np
import pylab
import urllib

# let's fetch the data
urllib.request.urlretrieve('https://goo.gl/mjDtMB', 'hourly.pkl')

import pickle
hourly = pickle.load(open('hourly.pkl', 'rb'))
hourly[:10]

array([[21,  1,  1,  0,  3],
       [18,  1,  1,  1,  3],
       [ 0,  1,  1,  2,  3],
       [ 0,  1,  1,  3,  3],
       [ 0,  1,  1,  4,  3],
       [ 0,  1,  1,  5,  3],
       [ 3,  1,  1,  6,  3],
       [12,  1,  1,  7,  3],
       [ 4,  1,  1,  8,  3],
       [11,  1,  1,  9,  3]])

Now we can ask questions of these data. 

What was the largest number books read in any hour?

In [2]:
np.max(hourly[:,0])

1632

What was the index of that maximum?

In [3]:
np.argmax(hourly[:,0])

2147

What monday, day and hour was that?

In [3]:
hourly[np.argmax(hourly[:,0]), 1:4]

array([ 3, 31, 11])

What was the average daily time of the maximum? This happens to work because the index for the rows is the same as the time.

In [4]:
def F3(A):
    B = np.reshape(A[:,0], (-1, 24))
    return np.mean(np.argmax(B, axis=1))
F3(hourly)

13.117808219178082

How many hours were no books read?

In [5]:
def F4(A):
    return np.count_nonzero(A[:,0] == 0)
F4(hourly)

47

We could solve that with a loop.

In [6]:
def F4loop(A):
    cnt = 0
    for i in range(len(A)):
        if A[i,0] == 0:
            cnt = cnt + 1
    return cnt
F4loop(hourly)

47

What is the length of the longest run of hours with 0 books read?

First we'll just get the run length. I'm decorating my function with a print so I can see what is happening. This doesn't work yet, I'm just doing part of the problem.

In [8]:
def F5(A):
    C = A[:,0] # isolate the counts
    run = 0 # start with a run length of 0
    for i in range(len(C)): # visit every count
        if C[i] == 0: # if it is zero
            run = run + 1 # increase the run length
            print(i, run) # print so we can see what is happening
        else: # if it isn't zero
            run = 0 # reset the run length to 0
F5(hourly)

2 1
3 2
4 3
5 4
98 1
221 1
245 1
246 2
1586 1
3914 1
4059 1
4338 1
4339 2
4340 3
4341 4
4342 5
4343 6
4344 7
4345 8
4346 9
4347 10
4348 11
4349 12
4350 13
4583 1
4900 1
5429 1
6435 1
7613 1
7877 1
8450 1
8473 1
8475 1
8477 1
8572 1
8574 1
8576 1
8592 1
8597 1
8598 2
8599 3
8642 1
8644 1
8668 1
8713 1
8741 1
8742 2


Now let's modify the code above to keep track of the longest run.

In [7]:
def F5(A):
    C = A[:,0]
    run = 0
    maxrun = 0
    for i in range(len(C)):
        if C[i] == 0:
            run = run + 1
            print(i, run)
        else:
            run = 0
        if run > maxrun:
            maxrun = run
    return maxrun
F5(hourly)

2 1
3 2
4 3
5 4
98 1
221 1
245 1
246 2
1586 1
3914 1
4059 1
4338 1
4339 2
4340 3
4341 4
4342 5
4343 6
4344 7
4345 8
4346 9
4347 10
4348 11
4349 12
4350 13
4583 1
4900 1
5429 1
6435 1
7613 1
7877 1
8450 1
8473 1
8475 1
8477 1
8572 1
8574 1
8576 1
8592 1
8597 1
8598 2
8599 3
8642 1
8644 1
8668 1
8713 1
8741 1
8742 2


13

I like this one a little better because it only checks for the max when it might have changed.

In [8]:
def F5(A):
    C = A[:,0]
    run = 0
    maxrun = 0
    for i in range(len(C)):
        if C[i] == 0:
            run = run + 1
            if run > maxrun:
                maxrun = run
        else:
            run = 0
    return maxrun
F5(hourly)

2 1
3 2
4 3
5 4
4342 5
4343 6
4344 7
4345 8
4346 9
4347 10
4348 11
4349 12
4350 13


13

Let's check on that long run. Yes, I think we had the machine down that weekend for some power work.

In [9]:
hourly[4342-5:4342+20]

array([[  1,   6,  30,  17,   1],
       [  0,   6,  30,  18,   1],
       [  0,   6,  30,  19,   1],
       [  0,   6,  30,  20,   1],
       [  0,   6,  30,  21,   1],
       [  0,   6,  30,  22,   1],
       [  0,   6,  30,  23,   1],
       [  0,   7,   1,   0,   2],
       [  0,   7,   1,   1,   2],
       [  0,   7,   1,   2,   2],
       [  0,   7,   1,   3,   2],
       [  0,   7,   1,   4,   2],
       [  0,   7,   1,   5,   2],
       [  0,   7,   1,   6,   2],
       [  7,   7,   1,   7,   2],
       [ 68,   7,   1,   8,   2],
       [163,   7,   1,   9,   2],
       [460,   7,   1,  10,   2],
       [111,   7,   1,  11,   2],
       [214,   7,   1,  12,   2],
       [114,   7,   1,  13,   2],
       [ 80,   7,   1,  14,   2],
       [ 68,   7,   1,  15,   2],
       [ 56,   7,   1,  16,   2],
       [ 78,   7,   1,  17,   2]])