# Notes for 19 October

What does this code do? Hint: It accepts a mutable sequence (array or list) as its argument.

In [2]:
import numpy as np

What does this do?

In [3]:
def f1(A):
    A = A.copy() # make a copy so we don't change the original
    for i in range(1, len(A)):
        for j in range(i, 0, -1):
            if A[j-1] > A[j]:
                A[j-1], A[j] = A[j], A[j-1]
            else:
                break
    return A


In [4]:
f1(np.random.randint(0,10,5))

array([2, 3, 3, 5, 7])

We figured out that it sorts the input list.

That tricky line

    A[j-1], A[j] = A[j], A[j-1]
    
is equivalent to the 3 lines below.

In [5]:
def f2(A):
    A = A.copy() # make a copy so we don't change the original
    for i in range(1, len(A)):
        for j in range(i, 0, -1):
            if A[j-1] > A[j]:
                #A[j-1], A[j] = A[j], A[j-1]
                t = A[j-1]
                A[j-1] = A[j]
                A[j] = t
            else:
                break
    return A


In [6]:
A = np.random.randint(0,10,5)
print(A)
print(f2(A))

[9 9 9 2 0]
[0 2 9 9 9]


A broken version so we can see why we need that variable `t` above.

In [9]:
def f3(A):
    A = A.copy() # make a copy so we don't change the original
    for i in range(1, len(A)):
        for j in range(i, 0, -1):
            if A[j-1] > A[j]:
                #A[j-1], A[j] = A[j], A[j-1]
                # this is broken
                A[j] = A[j-1]
                A[j-1] = A[j]
            else:
                break
    return A


In [10]:
A = np.random.randint(0,10,5)
print(A)
print(f3(A))

[8 5 4 4 7]
[8 8 8 8 8]


Let's decorate our function with print calls so we can see what is happening.

In [11]:
def f1p(A):
    A = A.copy() # make a copy so we don't change the original
    for i in range(1, len(A)):
        print('i=', i)
        for j in range(i, 0, -1):
            print('j=', j)
            if A[j-1] > A[j]:
                print('swap', j-1, j)
                A[j-1], A[j] = A[j], A[j-1]
            else:
                print('break')
                break
            print(A)
    return A

In [12]:
f1p([4,3,2,1])

i= 1
j= 1
swap 0 1
[3, 4, 2, 1]
i= 2
j= 2
swap 1 2
[3, 2, 4, 1]
j= 1
swap 0 1
[2, 3, 4, 1]
i= 3
j= 3
swap 2 3
[2, 3, 1, 4]
j= 2
swap 1 2
[2, 1, 3, 4]
j= 1
swap 0 1
[1, 2, 3, 4]


[1, 2, 3, 4]

In [13]:
f1p([1,2,3,4])

i= 1
j= 1
break
i= 2
j= 2
break
i= 3
j= 3
break


[1, 2, 3, 4]