# Midterm Exam 2 Preview

This is a preview of the second midterm exam for Comp 116 in fall 2016. The dataset for the exam will have the same form as this one. It may have a different number of days (rows) but will have the same number of columns.

You **may** use any Python features. Many questions will be easy to answer using Numpy functions. Feel free to use them. You don't have to write a loop for every question.

The solution of every question **must** be a function. Simply computing the result is insufficient, you must write a function that depends only on the input arguments and produces the correct result.

You **may not use the Internet** for anything except retrieving and submitting your exam. Any other use will be a violation of the Honor Code. 

You may use any resources that you have stored locally on your computer or any paper notes, books, etc.

Of course you may **not** use any phones, friends, etc.

Enter your onyen below.

In [1]:
Author = 'zewalker' # not your pid, your onyen

## Honor Pledge

I certify that no unauthorized assistance has been received or given in the completion of this work. 

Enter your full name as the value of the Pledge variable below.

In [2]:
Pledge = 'Zachary Walker' # type your full name between the quotes

## Set up

I will set up the environment for you here. Do not modify any of this.

In [3]:
%matplotlib inline
import numpy as np
import pylab
import comp116

check, report = comp116.start('Midterm2Preview')

## Data

You are given a dataset describing of number of books read on [Tar Heel Reader](http://tarheelreader.org) during each hour in a recent year. 

The array has N rows of 5 columns which are: number of books read, month number (1-12), day of month (1-31), hour of day (0-23), weekday (0-6) Monday is 0. 

I'll load the data for you here. Don't change any of this.

In [4]:
import pickle
hourly = pickle.load(open('hourly.pkl', 'rb'))
hourly[:10]

array([[21,  1,  1,  0,  3],
       [18,  1,  1,  1,  3],
       [ 0,  1,  1,  2,  3],
       [ 0,  1,  1,  3,  3],
       [ 0,  1,  1,  4,  3],
       [ 0,  1,  1,  5,  3],
       [ 3,  1,  1,  6,  3],
       [12,  1,  1,  7,  3],
       [ 4,  1,  1,  8,  3],
       [11,  1,  1,  9,  3]])

You can see from the above that the data begins with 21 books being read between midnight and 1AM on January 1st which was a Thursday.

## Questions

Think about the kinds of questions you might ask of these data? I've give you a few samples below but the exam questions will not be limited to these topics.

### 1. How many full days of data do we have?

Your answer must be a function named `F1` that takes a single argument and returns the integer answer.

In [5]:
def F1(x):
    a= int(len(x[:,1])/24)
    return a
# Write your function here


# let's see what your function returns
print('F1 returns', F1(hourly))

check('Q1', F1, hourly, points=10)

F1 returns 365
Q1 function signature appears correct
Q1-result appears correct


### 2. How many books were read Monday through Friday?

Write a function named `F2` that takes a single argument and returns the integer answer.

In [105]:
def F2(a):
    b= 0
    for i in range(len(a[:,4])):
        if a[i,4] < 5:
            b= b + a[i,0]
    return b# write your function here

print('F2 returns', F2(hourly))
check('Q2', F2, hourly, points=15)

F2 returns 1226412
Q2 function signature appears correct
Q2-result appears correct


### 3. How many books were read in each month?

Write a function named `F3` that takes the data array and return 12 element integer array of the total number of books read each month. 

In [107]:
def F3(a):
    b= np.zeros(12, dtype=int)
    for x in range(12):
        for y in range(len(a[:,0])):
            if a[y,1] == x+1:
                b[x]= int(int(b[x])+ int(a[y,0]))
    return b
                # Write your function here

print('F3 returns', F3(hourly))
check('Q3', F3, hourly, points=15)

F3 returns [120951 131836 157986 143006 106184  54838  44223  55686 127004 153947
 140419  92533]
Q3 function signature appears correct
Q3-result appears correct


### 4. What is the average number of books read each day before the hour that has the maximum number of books that day?

For example suppose the number of books read each hour for a day were:

    21 18 0 0 0 0 3 12 4 11 11 22 42 15 17 49 18 26 57 90 35 23 65 15

The maximum, 90, occurred in hour 19 so we want to accumulate the first 18 values for a total of 269 books for this day. Do a similar process for each day and average the result.

Write a function `F4` that takes a single argument and returns the floating point average.

In [110]:
def F4(A):
    B = A[:,0]
    Total = 0
    C= np.reshape(B, (-1,24))
    for i in range(len(C[:,0])):
        for j in range(len(C[0,:])):
            if j < np.argmax(C[i]):
                Total= Total + C[i,j]
    return Total/len(C[:,0])
        
    # write your code here
print('F4 returns', F4(hourly))
check('Q4', F4, hourly, points=20)

F4 returns 1279.85205479
Q4 function signature appears correct
Q4-result appears correct


### 5. How many books were read on the given month and day?

Write a function named `F5` that takes three arguments, the data, the month, and the day and returns the total number of books read that day.

In [111]:
def F5(data, month, day):
    A = data[data[:,1]==month]
    B = A[A[:,2]==day, 0]
    C = np.sum(B)
    return C
    # write your code here
# test 1
print('F5 returns', F5(hourly, 5, 1))
check('Q5 test 1', F5, hourly, 5, 1, points=10)

# test 2
print('F5 returns', F5(hourly, 5, 2))
check('Q5 test 2', F5, hourly, 5, 1, points=10)

F5 returns 4921
Q5 test 1 function signature appears correct
Q5 test 1-result appears correct
F5 returns 835
Q5 test 2 function signature appears correct
Q5 test 2-result appears correct


In [10]:
def F6(x): #How many days had less than 1000 books read
    A= np.reshape(x[:,0], (-1,24))
    count =0 
    for i in range(len(A[:,0])):
        if np.sum(A[i,:]) < 1000:
            count= count + 1
    return count
F6(hourly)

75

In [16]:
def F7(x):#What is the difference between the average number of books read on a weekday and the average number of books read on a weekend day?
    weekdays = x[x[:,4] <= 4, 0]
    weekends = x[x[:,4] > 4, 0]
    return (np.mean(weekdays) - np.mean(weekends))*24
F7(hourly)

3716.1946286472148

In [27]:
def F8(x): #What is the average number of books read per day before noon in July?
    data= x[x[:,1] ==7]
    data = data[data[:,3] <12, 0]
    return np.mean(data)*12
F8(hourly)


717.0322580645161

In [36]:
def F9(day, data): #Write a function that takes in an integer representing a day of the month, and returns an array of the number of books read on that day for each month.
    oneDay = data[data[:,2]==day]
    return np.bincount(oneDay[:,1], oneDay[:,0])[1:]
F9(15, hourly)

array([ 6166.,  1670.,  1672.,  8004.,  4290.,  1879.,  2021.,   394.,
        6430.,  6373.,  2247.,  4745.])

In [48]:
def F10(x): #Which day of the week has the most number of books read and how many books were read on that day?
    A =[]
    for i in range(6):
        S= (x[x[:,4] == i, 0])
        T = np.sum(S)
        A.append(T)
    B = np.argmax(A)
    C= np.max(A)
    return B,C
F10(hourly)

(1, 274313)

In [60]:
def F11(data, month, day, starthour, endhour): #Write a function that takes in data, month, day, start hour and end hour and returns the total number of books read during that period of time.
    A= data[data[:,1]==month]
    B= A[A[:,2]==day]
    C= B[B[:,3]<=endhour]
    D= C[C[:,3]>= starthour, 0]
    return np.sum(D)
F11(hourly, 3, 21, 9, 21)

871

In [90]:
def F12(data): #Write a function that returns an array containing the average number of books read per month.
    means = np.zeros(12)
    for i in range(1,13):
        means[i-1]= np.mean(data[data[:,1]==i,0])
    return means
F12(hourly)

array([ 162.56854839,  196.18452381,  212.34677419,  198.61944444,
        142.72043011,   76.16388889,   59.43951613,   74.84677419,
        176.39444444,  206.91801075,  195.02638889,  124.37231183])

In [92]:
# could be useful 10-17 notes
def CountInt3(A):
    N = np.max(A) + 1
    time = np.zeros(N)
    for i in range(N):
        time[i] = np.count_nonzero(A == i)
    return time

In [96]:
def BooksOnDOW(data, dow): #We wrote a function to get the total number of books read on a given day of the week.
    return np.sum(data[data[:,4] == dow, 0])

In [95]:
def F3(A): #average daily time for the maxium
    B = np.reshape(A[:,0], (-1, 24))
    return np.mean(np.argmax(B, axis=1))
F3(hourly)

13.117808219178082

In [98]:
def F5(A): #longest run with no books read
    C = A[:,0]
    run = 0
    maxrun = 0
    for i in range(len(C)):
        if C[i] == 0:
            run = run + 1
            if run > maxrun:
                maxrun = run
        else:
            run = 0
    return maxrun
F5(hourly)

13

In [40]:
def F1(A, N): #maxmium run with less than N books read
    run = 0
    maxrun = 0
    for i in range(len(A)):
        if A[i,0] < N:
            if A[i, 4]>4:
                run = run + 1
                if run > maxrun:
                    maxrun = run
            #print(i, run)
        else:
            run = 0
    return maxrun
F1(hourly, 10)

9

In [101]:
def countVals(A): #couldbeuseful
    R = np.zeros(np.max(A)+1, dtype=int)
    for i in range(len(A)):
        R[A[i]] = R[A[i]] + 1
    return R

In [103]:
def F2(A): #longest run of increasing numbers plus that run
    run = 0
    maxrun = 0
    maxindex = 0
    for i in range(1, len(A)):
        if A[i,0] > A[i-1,0]:
            run = run + 1
            if run > maxrun:
                maxrun = run
                maxindex = i
            #print(i, run)
        else:
            run = 0
    print(maxrun, maxindex)
    return A[maxindex-maxrun:maxindex+1]
F2(hourly)   

9 7595


array([[  5,  11,  13,   2,   4],
       [  7,  11,  13,   3,   4],
       [ 10,  11,  13,   4,   4],
       [ 14,  11,  13,   5,   4],
       [ 74,  11,  13,   6,   4],
       [224,  11,  13,   7,   4],
       [348,  11,  13,   8,   4],
       [604,  11,  13,   9,   4],
       [697,  11,  13,  10,   4],
       [862,  11,  13,  11,   4]])

In [5]:
def week_sum(data):
    daily = np.reshape(data[:,0], (-1,24))
    daily_sums = np.sum(daily, axis=1)
    days_of_week = data[::24,4]
    week_sums = []
    current_week = 0
    for i in range(len(daily_sums)):
        if days_of_week[i] == 0:
            week_sums.append(current_week)
            current_week = 0
        current_week += daily_sums[i]
    if current_week:
        week_sums.append(current_week)
    return np.array(week_sums)
week_sum(hourly)

array([ 3044, 28092, 30541, 27979, 32988, 35831, 34573, 25592, 35704,
       34470, 35353, 34146, 38508, 27995, 30548, 38526, 34695, 32161,
       29401, 28084, 24372, 17360, 18111, 12998,  9811, 11358,  7531,
       10582, 10681, 10625,  9114,  7370, 10847, 12032, 19606, 21650,
       26106, 32173, 31209, 34325, 35292, 33094, 37412, 35281, 38756,
       36615, 39155, 17178, 35940, 31131, 24751,  5341,  2575])

In [7]:
def pairs(data): # number of pairs of code with same number of books read
    counts = np.bincount(data[:,0])
    return np.count_nonzero(counts == 2)
pairs(hourly)

211

In [8]:
def F18(A): #number of consecutive pairs 
    A = A[:,0]
    pairs = 0
    for i in range(1,len(A)):
        if A[i] == A[i-1]:
            if i+1==len(A) or A[i]!=A[i+1]:
                pairs = pairs+1
    return pairs
F18(hourly)

128

In [13]:
def F20(A): #How many hours had more books read than the same hour the previous day?
    count = 0
    A = np.reshape(A[:,0],(-1,24))
    for i in range(1,len(A)):
        count = count + np.count_nonzero(A[i] > A[i-1])
    return count
F20(hourly)

4275

In [39]:

hourly[:10]
F3(hourly, 1, 1, 1, 0, 1, 9)

UnboundLocalError: local variable 'end' referenced before assignment

### And more...

Your exam will have about 6 questions for a total of 100 points. Questions are not intended to be tricky. If there is a simple interpretation of the question, that is most likely what I expect from you. If you have any doubt, try it to see what the checker says.

In [10]:
report(Author, Pledge)

Q1 appears correct
Q1-result appears correct
Q2 appears correct
Q2-result appears correct
Q3 appears correct
Q3-result appears correct
Q4 appears correct
Q4-result appears correct
Q5 test 1 appears correct
Q5 test 1-result appears correct
Q5 test 2 appears correct
Q5 test 2-result appears correct
Report for zewalker
  Pledged on my honor: Zachary Walker
    zewalker
  12.0 of 12 possibly correct for up to 80.0 of 80 points
